name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Configure Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
          version: '330.0.0'
          project_id: ${{secrets.RUN_PROJECT}}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Build and deploy to Cloud Run
      uses: GoogleCloudPlatform/github-actions/cloud-run@v1
      with:
        image: gcr.io/elated-strength-380605/my-app
        service: pythonproject
        region: us-central1
        platform: managed




