name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: gcr.io/$PROJECT_ID/hello-world:$GITHUB_SHA
        builder: gcr.io/cloud-builders/docker
        file: ./Dockerfile

    - name: Deploy to Cloud Run
      uses: GoogleCloudPlatform/github-actions/cloud-run@main
      with:
        service_name: pythonproject
        image_uri: gcr.io/$PROJECT_ID/pythonproject:$GITHUB_SHA
        platform: managed
        project_id: $PROJECT_ID
        service_account_key: ${{ secrets.RUN_SA_KEY }}
