name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1


    - name: Build and deploy to Cloud Run
      uses: GoogleCloudPlatform/github-actions/cloud-run@v1
      with:
        image: gcr.io/elated-strength-380605/my-app
        service: pythonproject
        region: us-central1
        platform: managed




