name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{secrets.RUN_PROJECT}}
  SERVICE_NAME: pythonproject
  REGION: us-central1
  IMAGE_NAME: pythonproject

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '342.0.0'
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest

      - name: Configure the Cloud Run service
        run: |
          gcloud config set project ${{ env.PROJECT_ID }}
          gcloud config set run/region ${{ env.REGION }}
          gcloud services enable run.googleapis.com

      - name: Deploy the container to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service-name: ${{ env.SERVICE_NAME }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest
          region: ${{ env.REGION }}
          platform: managed
          memory: 256Mi
          max-instances: 1
          concurrency: 80
          service-account: ${{ secrets.GCP_SA_EMAIL }}



  #niche thi
  name: Deploy to Google Cloud Run

  on:
    push:
      branches:
        - master

  env:
    PROJECT_ID: ${{secrets.RUN_PROJECT}}
    SERVICE_NAME: pythonproject
    REGION: us-central1
    IMAGE_NAME: pythonproject

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.9'

        - name: Set up Google Cloud SDK
          uses: google-github-actions/setup-gcloud@v1
          with:
            version: '342.0.0'
            project_id: ${{ env.PROJECT_ID }}
            service_account_key: ${{ secrets.GCP_SA_KEY }}




        - name: Configure Docker
          uses: docker/setup-buildx-action@v1

        - name: Build the Docker image
          uses: docker/build-push-action@v2
          with:
            context: .
            push: false
            tags: gcr.io/${{ env.PROJECT_ID }}${{ env.IMAGE_NAME }}:latest
  #
  #      - name: Configure the Cloud Run service
  #        run: |
  #          gcloud config set project ${{ env.PROJECT_ID }}
  #          gcloud config set run/region ${{ env.REGION }}
  #          gcloud services enable run.googleapis.com

  #      - name: Deploy the container to Cloud Run
  #        uses: google-github-actions/deploy-cloudrun@main
  #        with:
  #          service-name: pythonproject
  #          image: gcr.io/${{ env.PROJECT_ID }}${{ env.IMAGE_NAME }}:latest --service pythonproject
  #          region: ${{ env.REGION }}
  #          platform: managed
  #          memory: 256Mi
  #          max-instances: 1
  #          concurrency: 80
  #          service-account: ${{ secrets.GCP_SA_EMAIL }}



